// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Announcement {
  id: string;
  slug: string | null;
  status: string;
  message: string;
  location?: string;
  href?: string;
  enabled?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Banner {
  id: string;
  slug: string | null;
  status: string;
  internal_name: string;
  eyebrow?: string;
  headline: string;
  body?: PortableTextBlock[];
  primary_cta_label?: string;
  primary_cta_href?: string;
  secondary_cta_label?: string;
  secondary_cta_href?: string;
  theme?: string;
  alignment?: string;
  bg_type?: string;
  bg_css?: string;
  bg_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_focal_point?: string;
  bg_video_url?: string;
  bg_video_poster?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_overlay?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface CategoryTile {
  id: string;
  slug: string | null;
  status: string;
  label: string;
  description?: string;
  href: string;
  size?: string;
  bg_css?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HeroSlide {
  id: string;
  slug: string | null;
  status: string;
  eyebrow?: string;
  headline: string;
  subtitle?: string;
  cta_label?: string;
  cta_href?: string;
  bg_type?: string;
  bg_css?: string;
  bg_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_focal_point?: string;
  bg_video_url?: string;
  bg_video_poster?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_overlay?: string;
  accent_css?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  cover_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  cover_gradient?: string;
  author_name?: string;
  published_date?: string;
  reading_minutes?: number;
  body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Product {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery_2?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery_3?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery_4?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery_5?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  description?: PortableTextBlock[];
  type: string;
  sku: string;
  prices: unknown;
  manage_stock?: boolean;
  stock_quantity?: number;
  stock_status: string;
  backorders?: string;
  low_stock_threshold?: number;
  weight_grams?: number;
  tax_class?: string;
  shipping_class_slug?: string;
  featured?: boolean;
  is_downloadable?: boolean;
  is_virtual?: boolean;
  downloadable_files?: unknown;
  subscription_config?: unknown;
  child_product_ids?: unknown;
  product_url?: string;
  button_text?: string;
  vendor_id?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SectionHeader {
  id: string;
  slug: string | null;
  status: string;
  label: string;
  eyebrow?: string;
  title: string;
  subtitle?: string;
  cta_label?: string;
  cta_href?: string;
  render_mode?: string;
  theme?: string;
  alignment?: string;
  bg_type?: string;
  bg_css?: string;
  bg_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_focal_point?: string;
  bg_video_url?: string;
  bg_video_poster?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  bg_overlay?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteText {
  id: string;
  slug: string | null;
  status: string;
  bento_eyebrow?: string;
  bento_title?: string;
  products_eyebrow?: string;
  products_title?: string;
  journal_eyebrow?: string;
  journal_title?: string;
  journal_sub?: string;
  footer_tagline?: string;
  footer_newsletter_title?: string;
  footer_newsletter_body?: string;
  footer_newsletter_placeholder?: string;
  footer_newsletter_cta?: string;
  footer_copyright?: string;
  social_instagram?: string;
  social_twitter?: string;
  social_pinterest?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TrustItem {
  id: string;
  slug: string | null;
  status: string;
  icon?: string;
  title: string;
  description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    announcements: Announcement;
    banners: Banner;
    category_tiles: CategoryTile;
    hero_slides: HeroSlide;
    posts: Post;
    products: Product;
    section_headers: SectionHeader;
    site_text: SiteText;
    trust_items: TrustItem;
  }
}